In [1]:
#import lib
import math
import numpy as np
import time
import copy
import random as rd
from scipy import special

In [2]:
#define function
def s(x):
    return 1/(1+math.exp(-x))
#0.8807970779778823
print(s(2))
def s_prime(x):
    return math.exp(-x)/((1+math.exp(-x))**2)
def normal_random():
    return math.sqrt(2)*special.erfinv(2*rd.random()-1)
print(s_prime(2))

0.8807970779778823
0.1049935854035065


In [3]:
#create network

neuron_number=[3,4,5]

print('value')
network=[]
for i in neuron_number:
    network.append(np.array([0.0]*i))
for i in range(len(network)):
    for j in range(len(network[i])):
        network[i][j]=normal_random()
    print(network[i])
        

weight=[]
for i in range(len(neuron_number)-1):
    weight.append(np.array([[0.0]*neuron_number[i+1]]*neuron_number[i]))
print('network weight')
for i in weight:
    for j in range(len(i)):
        i[j]=normal_random()
    print(i)
print()
bias=[]
for i in range(len(neuron_number)-1):
    bias.append(np.array([0.0]*neuron_number[i+1]))
print('network bias')
for i in bias:
    for j in range(len(i)):
        i[j]=normal_random()
    print(i)

value
[0.42140346 0.55973206 0.13986221]
[ 0.9115653   1.02199075  0.27492499 -0.48419631]
[ 1.17571212  1.01186715  0.07632553 -1.24848335  0.33473578]
network weight
[[ 0.21672874  0.21672874  0.21672874  0.21672874]
 [ 0.44913084  0.44913084  0.44913084  0.44913084]
 [-1.1442339  -1.1442339  -1.1442339  -1.1442339 ]]
[[ 1.26774394  1.26774394  1.26774394  1.26774394  1.26774394]
 [ 0.80804178  0.80804178  0.80804178  0.80804178  0.80804178]
 [ 0.20039292  0.20039292  0.20039292  0.20039292  0.20039292]
 [-1.5201878  -1.5201878  -1.5201878  -1.5201878  -1.5201878 ]]

network bias
[-0.01458079 -0.3404531  -1.12430711  0.07054279]
[-0.47501888 -0.60590498 -0.01169228  0.98676679  0.06895601]


In [4]:
test_data=np.array([[1,2,3]])
label=np.array([1,0,0,0,0])
network[0]=test_data[0]

In [7]:
epoch=100
for times in range(epoch):

    for i in range(1,len(network)):
        tmp=np.dot(network[i-1],weight[i-1])+bias[i-1]
        for j in range(len(tmp)):
            tmp[j]=s(tmp[j])
        network[i]=tmp
    output_data=network[-1]
    error=(np.sum((output_data-label)**2))
    print(error)



    de_a=[]
    de_b=[]
    for i in range(len(neuron_number)-1):
        de_a.append(np.array([[0.0]*neuron_number[i+1]]*neuron_number[i]))
        de_b.append(np.array([0.0]*neuron_number[i+1]))


    for m in range(len(de_a[-1])):
        for n in range(len(de_a[-1][m])):
            tmp_s_prime=0
            for i in range(len(network[-2])):
                tmp_s_prime+=(weight[-1][i][n]*network[-2][i])
            tmp_s_prime+=bias[-1][n]
            de_a[-1][m][n]=2*(output_data[n]-label[n])*s_prime(tmp_s_prime)*network[-2][m]
            de_b[-1][n]=2*(output_data[n]-label[n])*s_prime(tmp_s_prime)

    for m in range(len(de_a[-2])):
        for n in range(len(de_a[-2][m])):
            y_s_prime=np.zeros(len(network[-1]))
            for i in range(len(network[-2])):
                for j in range(len(y_s_prime)):
                    y_s_prime[j]+=(weight[-1][i][j]*network[-2][i])


            for i in range(len(y_s_prime)):
                y_s_prime[j]+=bias[-1][i]
                y_s_prime[j]=s_prime(y_s_prime[j])

            x_s_prime=0
            for i in range(len(network[-3])):
                x_s_prime+=(weight[-2][i][n]*network[-3][i])
            x_s_prime+=bias[-2][n]
            x_s_prime=s_prime(x_s_prime)
            tmp=0
            for i in range(len(network[-1])):
                tmp+=(2*(output_data[i]-label[i])*y_s_prime[i]*weight[-1][n][i])
            tmp*=x_s_prime
            de_b[-2][n]=tmp
            tmp*=network[-3][m]
            de_a[-2][m][n]=tmp



    for i in range(len(weight)):
        weight[i]-=(de_a[i])
    for i in range(len(bias)):
        bias[i]-=(de_b[i])

0.09749040314019233
0.09212055436955298
0.08728074845503514
0.0828981135665253
0.0789123595724927
0.07527320214609406
0.07193838981323966
0.06887217661518057
0.0660441279818171
0.06342817849498467
0.06100188201350079
0.058745810101964675
0.056643065816816995
0.054678887972562415
0.052840326932385204
0.051115977355182994
0.04949575661260852
0.047970720065394004
0.04653290627137735
0.045175206641251325
0.043891255172896375
0.04267533476212885
0.041522297266396516
0.040427495032613
0.03938672202404321
0.03839616301887031
0.037452349623707734
0.036552122063323284
0.035692595884318765
0.034871132854045875
0.03408531545331156
0.033332924457660104
0.03261191918131103
0.03192042002342887
0.03125669301087345
0.03061913607698155
0.03000626685390291
0.02941671178788428
0.02884919641372713
0.028302536647306666
0.02777563097423913
0.027267453429093598
0.026777047273439214
0.026303519292888163
0.02584603464345585
0.025403812186284687
0.02497612025728039
0.024562272824679113
0.024161625993150773
0.02

In [8]:
print(output_data)

[0.9698792  0.05570047 0.05463004 0.05269537 0.05447286]


In [ ]:
test=np.zeros(2)
test[0]+=0.01
print(test)

In [ ]:
delta_a2=np.array([[0.0]*neuron_number[i+1]]*neuron_number[i])
for m in range(len(delta_a2)):
    for n in range(delta_a2[i]):
        delta_a2[m][n]=2*(output_data[0][n]-label[0][n])*s_prime()

In [ ]:
test_1=[[1,2,3]]
test_2=[
    [1,2],
    [1,2],
    [1,2]
]
print(np.dot(np.array(test_1),np.array(test_2)))